---
name: build_using_renv__R_4.5.0__py_3.11__bioC_3.21

env:
  RVERSION: 4.5.0
  PYVERSION: 3.11
  
on:
  workflow_dispatch: null
  pull_request:

jobs:
  build_ubuntu_24:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install sys deps
        run: |
          sudo apt update && sudo apt install -y libcurl4-openssl-dev \
            libcairo2-dev libssl-dev make  unixodbc-dev libnode-dev \
            libxml2-dev libx11-dev git libfontconfig1-dev libfreetype6-dev \
            zlib1g-dev libglpk-dev libjpeg-dev libmagick++-dev gsfonts \
            cmake libpng-dev libtiff-dev python3 libglu1-mesa-dev libgl1-mesa-dev \
            libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev libsodium-dev \
            libicu-dev tcl tk tk-dev tk-table libfribidi-dev libharfbuzz-dev libudunits2-dev
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "$PYVERSION"
          cache: 'pip'
      - name: pip install reqs
        shell: bash
        run: |
          pip install -r requirements.txt
      - name: Check env and python version
        run: |
          python --version
          echo -e '\n\n'
          env
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '$RVERSION'
      - name: Set up renv and install renv.lock packages
        uses: r-lib/actions/setup-renv@v2
      - name: Check R and python versions
        id: get-version
        shell: Rscript {0}
        run: |
          sessionInfo()$running
          R.Version()$version.string
          renv::status()
          system('python --version')
      - name: Install rmarkdown (how are the vignettes being built?)
        shell: Rscript {0}
        run: |
          install.packages('rmarkdown')        
      - name: Attempt to render the vignettes (how is this suposed to work?)
        shell: Rscript {0}
        run: |
          rmarkdown::render('code/00-about.qmd')
