---
name: render_vignettes

on:
  workflow_dispatch: null
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python-version: ["3.11", "3.12", "3.13"]
        r-version: ["4.5.0"]
        requirements: ["requirements.txt", "requirements_versionless.txt", "requirements_semipinned.txt"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install sys deps
        run: |
          sudo apt update && sudo apt install -y pandoc libcurl4-openssl-dev \
            libcairo2-dev libssl-dev make  unixodbc-dev libnode-dev \
            libxml2-dev libx11-dev git libfontconfig1-dev libfreetype6-dev \
            zlib1g-dev libglpk-dev libjpeg-dev libmagick++-dev gsfonts \
            cmake libpng-dev libtiff-dev python3 libglu1-mesa-dev libgl1-mesa-dev \
            libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev libsodium-dev \
            libicu-dev tcl tk tk-dev tk-table libfribidi-dev libharfbuzz-dev libudunits2-dev \
            libfftw3-dev
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: pip install reqs
        shell: bash
        run: |
          pip install -r ${{ matrix.requirements }}
      - name: Check env and python version
        run: |
          python --version
          echo -e '\n\n'
          env
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Set up renv and install renv.lock packages
        uses: r-lib/actions/setup-renv@v2
      - name: Check R and python versions
        id: get-version
        shell: Rscript {0}
        run: |
          sessionInfo()$running
          R.Version()$version.string
          renv::status()
          system('python --version')
      #          
      # - name: Attempt to render the vignettes with rmarkdown
      #   shell: Rscript {0}
      #   run: |
      #     rmarkdown::render('code/00-home.qmd') #  code/00-overview-latSOD.qmd')
      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install quarto CRAN (how are the vignettes being built?)
        shell: Rscript {0}
        run: |
          renv::install('quarto')
          renv::status()
          .libPaths()
      # - name: Attempt to render the vignettes with quarto
      #  shell: Rscript {0}
      #  run: |
      #    quarto::quarto_render('code/00-overview-latSOD.qmd')
      - name: Fake HTML generation
        run: |
          quarto check &> docs/00-overview-latSOD.html
      - name: Debug updated renv
        shell: Rscript {0}
        run: |
          renv::status()
          library(quarto)
          .libPaths()       
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: home
          path: docs/00-overview-latSOD.html
