---
name: build_using_renv
on:
  workflow_dispatch: null
  pull_request:

jobs:
  build_ubuntu_latest:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up R (no python)
        uses: r-lib/actions/setup-r@v2
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
      # - name: Install and activate renv
      #   run: |
      #     install.packages("renv")
      #     renv::activate()
      #     shell: Rscript {0}
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Get R and OS version
        id: get-version
        run: |
          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
          shell: Rscript {0}
      # - name: Restore Renv package cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.RENV_PATHS_ROOT }}
      #     key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles('renv.lock') }}
      #     restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
      - name: Check python version - from subshell
        shell: Rscript {0}
        run: |
          renv::status()
          system('python --version')
